package leyendasolvidadas.dominio.misiones;

/** Identificador estable de una misión, independiente de su título visible. */
public enum MisionId {
    BATIDA_CAZA,
    CARTOGRAFIAR_PARAJE,
    RELIQUIA_PERDIDA,
    CABEZA_BESTIA,
    SOGAS_VACIAS,
    SENDERO_QUE_REGRESA,
    MEDALLA_AHORCADO,
    RESPIRAN_BARRO,
    TUMBA_ALDARA,
    CAMPANAS_SIN_CAMPANERO,
    PAGINA_SIN_NOMBRES,
    HIERRO_PARA_MUERTOS,
    GALERIAS_BAJO_PAZO,
    CRIADOS_SIN_NOMBRE,
    INVENTARIO_CULPABLES,
    TABLILLAS_PATIBULO,
    LETANIA_AUSENTES,
    ARBOL_CULPA,
    REY_SOGAS,
    SUDARIOS_ALDARA,
    PUERTAS_HOSPITAL,
    CAMPANA_CAPATAZ,
    CRIPTA_SOUTOMAIOR,
    VIGILIA_CIENTO_DOCE,
    ULTIMA_PROCESION,
    MISION_PERSONAL
}
